/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>
#include "STM32F411xx.h"
#include "DHT22.h"
#include "GPTimer_Driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	DHT22_DS_t data;
	// 1. Initialize TIMER 2
	TIMx_Delay_ms_Init(TIM2);
	// 2. Intialize DHT22 Sensor
	DHT22_Init(GPIOC, GPIO_PIN_10);
	/* Loop forever */
	for (;;) {
		uint8_t status = DHT22_Read(GPIOC, GPIO_PIN_10, &data.Temperature, &data.Humidity);
		printf("Status of DHT22 Read: %d\n", status);
		TIMx_Delay_ms(TIM2, 2000); // 2s delay
	}
}
