/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>

#include "STM32F411xx.h"
#include "GPIO_Driver.h"
#include "GPTimer_Driver.h"
#include "SPI_Driver.h"
#include "SYSTICK_Driver.h"
#include "NVIC.h"

#define SYSTEM_FREQUENCY	16000000
#define TIMER_FREQUENCY		1000

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
	#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


//Test function
// void GPIO_Init(GPIOx_Handle_t *pGPIOxHandle);

/*
 * Exercise - Test the SPI_SendData API to send the string "hello world" and use the below configuration
 * 1. SPI2 in Master mode
 * 2. SCLK - max possible
 * 3. DFF = 0 & DFF = 1
*/

/*
 * Pinouts documented for SPI2 Peripheral being used
 * MOSI -> PB15 - CN10 : 26
 * MISO -> PB14 - CN10 : 28
 * SCK --> PB13 - CN10 : 30
 * NSS --> PB12 - CN10 : 16
*/

void SPI2_GPIOInit(void){
	//Create a GPIO Handle and perform configure
	GPIOx_Handle_t SPIPins;

	SPIPins.pGPIOx_Base = GPIOB;
	SPIPins.GPIO_PinConfig.GPIOx_PinMode = GPIO_MODE_ALTERNATE;
	SPIPins.GPIO_PinConfig.GPIOx_PinAltFunMode = GPIO_AFR_AF5;
	SPIPins.GPIO_PinConfig.GPIOx_PinOPType = GPIO_OUTPUT_PUSH_PULL;
	SPIPins.GPIO_PinConfig.GPIOx_PinSpeed = GPIO_SPEED_FAST;
	SPIPins.GPIO_PinConfig.GPIOx_PinPUPDControl = GPIO_PUPD_NA;

	//Initialize MOSI Pin
	SPIPins.GPIO_PinConfig.GPIOx_PinNumber = GPIO_PIN_15;
	GPIOx_Init(&SPIPins);

	//Initialize MISO Pin
	SPIPins.GPIO_PinConfig.GPIOx_PinNumber = GPIO_PIN_14;
	GPIOx_Init(&SPIPins);

	//Initialize SCK
	SPIPins.GPIO_PinConfig.GPIOx_PinNumber = GPIO_PIN_13;
	GPIOx_Init(&SPIPins);

	//Initialize NSS
	SPIPins.GPIO_PinConfig.GPIOx_PinNumber = GPIO_PIN_12;
	GPIOx_Init(&SPIPins);

	//SPI Pins configured!
}


void SPI2_Init(void){
	//Configure and Initialize SPI2 peripheral
	SPIx_Handle_t SPI2_Handle;

	SPI2_Handle.pSPIx = SPI2;
	SPI2_Handle.SPIx_Config.SPI_DEVICE_MODE = SPI_DEVICE_MODE_MASTER;
	SPI2_Handle.SPIx_Config.SPI_BUS_CONFIG = SPI_BUS_CONFIG_FULL_DUPLEX;
	SPI2_Handle.SPIx_Config.SPI_SCLK_SPEED = SPI_BAUDRATE_DIV2;
	SPI2_Handle.SPIx_Config.SPI_DFF = SPI_DFF_8BIT;

	//Configure to Mode 0
	SPI2_Handle.SPIx_Config.SPI_CPOL = SPI_CPOL_LOW;
	SPI2_Handle.SPIx_Config.SPI_CPHA = SPI_CPHA_LOW;

	//Enable Software Slave management for NSS
	SPI2_Handle.SPIx_Config.SPI_SSM = SPI_SSM_ENABLED;
	
	//Initialize SPI2 Peripheral
	SPI_Init(&SPI2_Handle);
}


int main(void)
{
	//Create a buffer
	char user_data[] = "Hello World";

	//Configure & Initialize SPI2 Peripheral
	SPI2_GPIOInit();
	SPI2_Init();

	//Configure SSI Bit
	SPI_SSI_Configure(SPI2, ENABLE);
	//or
	/*
	 * If Hardware slave mangement is enabled, then making SSOE bit 1 will make NSS Output Enable.
	 * The NSS Pin is automatically managed by the hardware i.e. when SPE = 1, NSS will be pulled to low.
	 * and NSS Pin will be high when SPE = 0
	*/
	//SPI_SSOE_Configure(SPI2, ENABLE);

	//Enable the SPI2 Peripheral
	SPI_Enable(SPI2);

	//Test SPI Send data API
	SPI_SendData(SPI2, (uint8_t *)user_data, strlen(user_data));

	//After transmission, we close or disable the SPI Peripheral
	//Disable the SPI2 Peripheral
	SPI_Disable_blocking(SPI2);

    /* Loop forever */
	for(;;){
		//
	}
}






//Test function to test new APIs created
// void GPIO_Init(GPIOx_Handle_t *pGPIOxHandle){
// 	//Test
// 	uint8_t pin = pGPIOxHandle->GPIO_PinConfig.GPIOx_PinNumber;
// 	uint8_t mode = pGPIOxHandle->GPIO_PinConfig.GPIOx_PinMode;
// 	uint8_t speed = pGPIOxHandle->GPIO_PinConfig.GPIOx_PinSpeed;
// 	uint8_t OPType = pGPIOxHandle->GPIO_PinConfig.GPIOx_PinOPType;
// 	uint8_t PUPDConfig = pGPIOxHandle->GPIO_PinConfig.GPIOx_PinPUPDControl;
// 	// uint8_t Altfun_Mode = pGPIOxHandle->GPIO_PinConfig.GPIOx_PinAltFunMode;

// 	//Enable Clock access for the peripheral
// //	GPIOx_PClkControl(GPIOA, CLK_EN);

// 	//1. Set GPIO pin mode
// 	GPIO_SetMode(pGPIOxHandle->pGPIOx_Base, pin, mode);

// 	//2. Set GPIO pin output type
// 	GPIO_SetOutputType(pGPIOxHandle->pGPIOx_Base, pin, OPType);

// 	//3. Set GPIO pin output speed
// 	GPIO_SetOutputSpeed(pGPIOxHandle->pGPIOx_Base, pin, speed);

// 	//4. Set GPIO pin pull up/down config
// 	GPIO_SetPullUpDown(pGPIOxHandle->pGPIOx_Base, pin, PUPDConfig);
// }
